### ISSUE TITLE
Training with spanish datasets? 

### ISSUE THREAD

**Issue by rmajasol** [nyrahealth/CrisperWhisper#2]
Hi, found this project from Laurin's response posted on this huggingface [thread](https://huggingface.co/spaces/openai/whisper/discussions/30#66dea3dd68f47ec63ecb9a98). My team and I are looking for a model that can detect these disfluencies (filler words, etc.) in the spanish language. Is this feature in your roadmap? If so, what ETA do you contemplate approximately? Thanks!

**Comment by LaurinmyReha** [comment]
Hey @rmajasol :) We do not intend to enable this feature anytime soon for spanish. However we hope that the recipe to extend these results to the spanish language is clear from the paper and this repo.
