### ISSUE TITLE
Plan to release smaller models

### ISSUE THREAD

**Issue by HKAB** [nyrahealth/CrisperWhisper#5]
Thanks for an interesting work! Do you guys have plan to release the finetune version of a smaller model like `small.en` or `medium.en`? It would be very useful!

**Comment by LaurinmyReha** [comment]
Thank you for checking it out.
We do not have fixed plans yet. We will certainly update the CrisperWhisper model and retrain when we collected and/or labelled more relevant data. This could take a while tough. When we do this i will make sure to also train smaller variants.
